// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/cat.proto

// Protobuf Java Version: 3.25.1
package com.example.cat;

public final class CatServiceProto {
  private CatServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CatServiceGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CatServiceGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CatServiceGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CatServiceGetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CatServiceGetResponseChild_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CatServiceGetResponseChild_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020schema/cat.proto\032\037google/protobuf/time" +
      "stamp.proto\"\"\n\024CatServiceGetRequest\022\n\n\002i" +
      "d\030\001 \001(\t\"\236\001\n\025CatServiceGetResponse\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004kind\030\003 \001(\t\022.\n\nbir" +
      "thed_at\030\004 \001(\0132\032.google.protobuf.Timestam" +
      "p\022-\n\010children\030\005 \003(\0132\033.CatServiceGetRespo" +
      "nseChild\"D\n\032CatServiceGetResponseChild\022\n" +
      "\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004kind\030\003 \001(\t2D" +
      "\n\nCatService\0226\n\003Get\022\025.CatServiceGetReque" +
      "st\032\026.CatServiceGetResponse\"\000B$\n\017com.exam" +
      "ple.catB\017CatServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_CatServiceGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CatServiceGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CatServiceGetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CatServiceGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CatServiceGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CatServiceGetResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Kind", "BirthedAt", "Children", });
    internal_static_CatServiceGetResponseChild_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CatServiceGetResponseChild_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CatServiceGetResponseChild_descriptor,
        new java.lang.String[] { "Id", "Name", "Kind", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
