// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/dog.proto

// Protobuf Java Version: 3.25.1
package com.example.dog;

public interface DogServiceGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DogServiceGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string kind = 3;</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 3;</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <code>.google.protobuf.Timestamp birthed_at = 4;</code>
   * @return Whether the birthedAt field is set.
   */
  boolean hasBirthedAt();
  /**
   * <code>.google.protobuf.Timestamp birthed_at = 4;</code>
   * @return The birthedAt.
   */
  com.google.protobuf.Timestamp getBirthedAt();
  /**
   * <code>.google.protobuf.Timestamp birthed_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBirthedAtOrBuilder();

  /**
   * <code>repeated .DogServiceGetRequestChild children = 5;</code>
   */
  java.util.List<com.example.dog.DogServiceGetRequestChild> 
      getChildrenList();
  /**
   * <code>repeated .DogServiceGetRequestChild children = 5;</code>
   */
  com.example.dog.DogServiceGetRequestChild getChildren(int index);
  /**
   * <code>repeated .DogServiceGetRequestChild children = 5;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .DogServiceGetRequestChild children = 5;</code>
   */
  java.util.List<? extends com.example.dog.DogServiceGetRequestChildOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .DogServiceGetRequestChild children = 5;</code>
   */
  com.example.dog.DogServiceGetRequestChildOrBuilder getChildrenOrBuilder(
      int index);
}
