// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: schema/dog.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.dog;

@kotlin.jvm.JvmName("-initializedogServiceGetRequest")
public inline fun dogServiceGetRequest(block: com.example.dog.DogServiceGetRequestKt.Dsl.() -> kotlin.Unit): com.example.dog.DogServiceGetRequest =
  com.example.dog.DogServiceGetRequestKt.Dsl._create(com.example.dog.DogServiceGetRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `DogServiceGetRequest`
 */
public object DogServiceGetRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.dog.DogServiceGetRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.dog.DogServiceGetRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.dog.DogServiceGetRequest = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.dog.DogServiceGetRequest.copy(block: `com.example.dog`.DogServiceGetRequestKt.Dsl.() -> kotlin.Unit): com.example.dog.DogServiceGetRequest =
  `com.example.dog`.DogServiceGetRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

