// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: schema/dog.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.dog;

@kotlin.jvm.JvmName("-initializedogServiceGetResponse")
public inline fun dogServiceGetResponse(block: com.example.dog.DogServiceGetResponseKt.Dsl.() -> kotlin.Unit): com.example.dog.DogServiceGetResponse =
  com.example.dog.DogServiceGetResponseKt.Dsl._create(com.example.dog.DogServiceGetResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `DogServiceGetResponse`
 */
public object DogServiceGetResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.dog.DogServiceGetResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.dog.DogServiceGetResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.dog.DogServiceGetResponse = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string kind = 3;`
     */
    public var kind: kotlin.String
      @JvmName("getKind")
      get() = _builder.getKind()
      @JvmName("setKind")
      set(value) {
        _builder.setKind(value)
      }
    /**
     * `string kind = 3;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     */
    public var birthedAt: com.google.protobuf.Timestamp
      @JvmName("getBirthedAt")
      get() = _builder.getBirthedAt()
      @JvmName("setBirthedAt")
      set(value) {
        _builder.setBirthedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     */
    public fun clearBirthedAt() {
      _builder.clearBirthedAt()
    }
    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     * @return Whether the birthedAt field is set.
     */
    public fun hasBirthedAt(): kotlin.Boolean {
      return _builder.hasBirthedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChildrenProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     */
     public val children: com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getChildrenList()
      )
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.add(value: com.example.dog.DogServiceGetRequestChild) {
      _builder.addChildren(value)
    }
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.plusAssign(value: com.example.dog.DogServiceGetRequestChild) {
      add(value)
    }
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.addAll(values: kotlin.collections.Iterable<com.example.dog.DogServiceGetRequestChild>) {
      _builder.addAllChildren(values)
    }
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.dog.DogServiceGetRequestChild>) {
      addAll(values)
    }
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     * @param index The index to set the value at.
     * @param value The children to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChildren")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.set(index: kotlin.Int, value: com.example.dog.DogServiceGetRequestChild) {
      _builder.setChildren(index, value)
    }
    /**
     * `repeated .DogServiceGetRequestChild children = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.dog.DogServiceGetRequestChild, ChildrenProxy>.clear() {
      _builder.clearChildren()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.dog.DogServiceGetResponse.copy(block: `com.example.dog`.DogServiceGetResponseKt.Dsl.() -> kotlin.Unit): com.example.dog.DogServiceGetResponse =
  `com.example.dog`.DogServiceGetResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.dog.DogServiceGetResponseOrBuilder.birthedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasBirthedAt()) getBirthedAt() else null

