// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: schema/cat.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.cat;

@kotlin.jvm.JvmName("-initializecatServiceGetResponse")
public inline fun catServiceGetResponse(block: com.example.cat.CatServiceGetResponseKt.Dsl.() -> kotlin.Unit): com.example.cat.CatServiceGetResponse =
  com.example.cat.CatServiceGetResponseKt.Dsl._create(com.example.cat.CatServiceGetResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `CatServiceGetResponse`
 */
public object CatServiceGetResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.cat.CatServiceGetResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.cat.CatServiceGetResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.cat.CatServiceGetResponse = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string kind = 3;`
     */
    public var kind: kotlin.String
      @JvmName("getKind")
      get() = _builder.getKind()
      @JvmName("setKind")
      set(value) {
        _builder.setKind(value)
      }
    /**
     * `string kind = 3;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     */
    public var birthedAt: com.google.protobuf.Timestamp
      @JvmName("getBirthedAt")
      get() = _builder.getBirthedAt()
      @JvmName("setBirthedAt")
      set(value) {
        _builder.setBirthedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     */
    public fun clearBirthedAt() {
      _builder.clearBirthedAt()
    }
    /**
     * `.google.protobuf.Timestamp birthed_at = 4;`
     * @return Whether the birthedAt field is set.
     */
    public fun hasBirthedAt(): kotlin.Boolean {
      return _builder.hasBirthedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChildrenProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     */
     public val children: com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getChildrenList()
      )
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.add(value: com.example.cat.CatServiceGetResponseChild) {
      _builder.addChildren(value)
    }
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.plusAssign(value: com.example.cat.CatServiceGetResponseChild) {
      add(value)
    }
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.addAll(values: kotlin.collections.Iterable<com.example.cat.CatServiceGetResponseChild>) {
      _builder.addAllChildren(values)
    }
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.cat.CatServiceGetResponseChild>) {
      addAll(values)
    }
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     * @param index The index to set the value at.
     * @param value The children to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChildren")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.set(index: kotlin.Int, value: com.example.cat.CatServiceGetResponseChild) {
      _builder.setChildren(index, value)
    }
    /**
     * `repeated .CatServiceGetResponseChild children = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChildren")
    public fun com.google.protobuf.kotlin.DslList<com.example.cat.CatServiceGetResponseChild, ChildrenProxy>.clear() {
      _builder.clearChildren()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.cat.CatServiceGetResponse.copy(block: `com.example.cat`.CatServiceGetResponseKt.Dsl.() -> kotlin.Unit): com.example.cat.CatServiceGetResponse =
  `com.example.cat`.CatServiceGetResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.cat.CatServiceGetResponseOrBuilder.birthedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasBirthedAt()) getBirthedAt() else null

