// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/cat.proto

// Protobuf Java Version: 3.25.1
package com.example.cat;

public interface CatServiceGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CatServiceGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
