name: Check Code Generation Diff

on:
  push:
    branches:
      - main

jobs:
  check_diff:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: proto

    steps:
      - uses: actions/checkout@v4

      - name: Run code generation
        run: make gen

      - name: Check diff
        run: |
          if git diff --exit-code; then
            echo "No code generation diff found."
          else
            echo "Code generation diff found. Please run 'make gen' locally and commit the changes."
            exit 1
          fi
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
      - run: make install
      - run: make lint
